# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35dfccd309d6e460bf254a6282c7994fa6879635c01c5b8d08e8d53ca910e94c0eae40ef7818335309e9c33db21b252733eda86342c70251777e92b1925e000b

test:
  secret_key_base: ea74fc287a3f81638053bf654b04c3310c3830cbee6dce759382fbcb5ca54e27d4d4f283d7f8ed74ad70201422890155798eb1a05bc3607496a9be9a07b2c099

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
